services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=shoppingDemo
      - MYSQL_ROOT_PASSWORD=Password1
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
